blank_issues_enabled: false
contact_links:
  - name: ğŸ™‹ Q&A / Discussion
    url: https://github.com/SSAFY-TBD/JOBJISIK/discussions
    about: ì§ˆë¬¸ì´ë‚˜ ì•„ì´ë””ì–´ëŠ” Discussionì— ì‘ì„±í•´ì£¼ì„¸ìš”.
